package com.iobits.budgetexpensemanager.utils

import com.iobits.budgetexpensemanager.ui.dataModels.MoneySymbol

object CountrySymbols {
     val countryList : ArrayList<MoneySymbol> = ArrayList()
    init {
        addCountryList()
    }
    private fun addCountryList(){
        countryList.apply {
          add(MoneySymbol("Afghanistan", "؋"))
          add(MoneySymbol("Albania", "L"))
          add(MoneySymbol("Algeria", "د.ج"))
          add(MoneySymbol("Andorra", "€"))
          add(MoneySymbol("Angola", "Kz"))
          add(MoneySymbol("Antigua and Barbuda", "$"))
          add(MoneySymbol("Argentina", "$"))
          add(MoneySymbol("Armenia", "֏"))
          add(MoneySymbol("Austria", "€"))
          add(MoneySymbol("Azerbaijan", "₼"))
          add(MoneySymbol("Bahamas", "$"))
          add(MoneySymbol("Bahrain", ".د.ب"))
          add(MoneySymbol("Bangladesh", "৳"))
          add(MoneySymbol("Barbados", "$"))
          add(MoneySymbol("Belarus", "Br"))
          add(MoneySymbol("Belgium", "€"))
          add(MoneySymbol("Belize", "BZ$"))
          add(MoneySymbol("Benin", "Fr"))
          add(MoneySymbol("Bhutan", "Nu."))
          add(MoneySymbol("Bolivia", "Bs"))
          add(MoneySymbol("Bosnia and Herzegovina", "KM or КМ"))
          add(MoneySymbol("Botswana", "P"))
          add(MoneySymbol("Brazil", "R$"))
          add(MoneySymbol("Brunei", "$"))
          add(MoneySymbol("Bulgaria", "лв"))
          add(MoneySymbol("Burkina Faso", "CFA"))
          add(MoneySymbol("Burundi", "Fr"))
          add(MoneySymbol("Cabo Verde", "$"))
          add(MoneySymbol("Cambodia", "៛"))
          add(MoneySymbol("Cameroon", "Fr"))
          add(MoneySymbol("Central African Republic", "FCFA"))
          add(MoneySymbol("Chad", "Fr"))
          add(MoneySymbol("Chile", "$"))
          add(MoneySymbol("China", "¥"))
          add(MoneySymbol("Colombia", "$"))
          add(MoneySymbol("Comoros", "Fr"))
          add(MoneySymbol("Congo", "Fr"))
          add(MoneySymbol("Costa Rica", "₡"))
          add(MoneySymbol("Croatia", "kn"))
          add(MoneySymbol("Cuba", "CUP"))
          add(MoneySymbol("Cyprus", "€"))
          add(MoneySymbol("Czech Republic", "Kč"))
          add(MoneySymbol("Denmark", "kr"))
          add(MoneySymbol("Djibouti", "Fr"))
          add(MoneySymbol("Dominica", "$"))
          add(MoneySymbol("Dominican Republic", "RD$"))
          add(MoneySymbol("East Timor", "$"))
          add(MoneySymbol("Ecuador", "$"))
          add(MoneySymbol("Egypt", "E£"))
          add(MoneySymbol("El Salvador", "$"))
          add(MoneySymbol("Equatorial Guinea", "Fr"))
          add(MoneySymbol("Eritrea", "Nfk"))
          add(MoneySymbol("Estonia", "€"))
          add(MoneySymbol("Eswatini", "E"))
          add(MoneySymbol("Ethiopia", "Br"))
          add(MoneySymbol("Fiji", "$"))
          add(MoneySymbol("Finland", "€"))
          add(MoneySymbol("France", "€"))
          add(MoneySymbol("Gabon", "Fr"))
          add(MoneySymbol("Gambia", "D"))
          add(MoneySymbol("Georgia", "₾"))
          add(MoneySymbol("Germany", "€"))
          add(MoneySymbol("Ghana", "₵"))
          add(MoneySymbol("Greece", "€"))
          add(MoneySymbol("Grenada", "$"))
          add(MoneySymbol("Guatemala", "Q"))
          add(MoneySymbol("Guinea", "Fr"))
          add(MoneySymbol("Guinea-Bissau", "CFA"))
          add(MoneySymbol("Guyana", "$"))
          add(MoneySymbol("Haiti", "G"))
          add(MoneySymbol("Honduras", "L"))
          add(MoneySymbol("Hungary", "Ft"))
          add(MoneySymbol("Iceland", "kr"))
          add(MoneySymbol("India", "₹"))
          add(MoneySymbol("Indonesia", "Rp"))
          add(MoneySymbol("Iran", "﷼"))
          add(MoneySymbol("Iraq", "ع.د"))
          add(MoneySymbol("Ireland", "€"))
          add(MoneySymbol("Israel", "₪"))
          add(MoneySymbol("Italy", "€"))
          add(MoneySymbol("Ivory Coast", "CFA"))
          add(MoneySymbol("Jamaica", "J$"))
          add(MoneySymbol("Japan", "¥"))
          add(MoneySymbol("Jordan", "د.ا"))
          add(MoneySymbol("Kazakhstan", "₸"))
          add(MoneySymbol("Kenya", "KSh"))
          add(MoneySymbol("Kiribati", "$"))
          add(MoneySymbol("Korea, North", "₩"))
          add(MoneySymbol("Korea, South", "₩"))
          add(MoneySymbol("Kosovo", "€"))
          add(MoneySymbol("Kuwait", "د.ك"))
          add(MoneySymbol("Kyrgyzstan", "лв"))
          add(MoneySymbol("Laos", "₭"))
          add(MoneySymbol("Latvia", "€"))
          add(MoneySymbol("Lebanon", "ل.ل"))
          add(MoneySymbol("Lesotho", "L"))
          add(MoneySymbol("Liberia", "$"))
          add(MoneySymbol("Libya", "ل.د"))
          add(MoneySymbol("Liechtenstein", "Fr"))
          add(MoneySymbol("Lithuania", "€"))
          add(MoneySymbol("Luxembourg", "€"))
          add(MoneySymbol("Madagascar", "Ar"))
          add(MoneySymbol("Malawi", "MK"))
          add(MoneySymbol("Malaysia", "RM"))
          add(MoneySymbol("Maldives", "ރ."))
          add(MoneySymbol("Mali", "Fr"))
          add(MoneySymbol("Malta", "€"))
          add(MoneySymbol("Marshall Islands", "$"))
          add(MoneySymbol("Mauritania", "UM"))
          add(MoneySymbol("Mauritius", "₨"))
          add(MoneySymbol("Mexico", "$"))
          add(MoneySymbol("Micronesia", "$"))
          add(MoneySymbol("Moldova", "L"))
          add(MoneySymbol("Monaco", "€"))
          add(MoneySymbol("Mongolia", "₮"))
          add(MoneySymbol("Montenegro", "€"))
          add(MoneySymbol("Morocco", "د.م."))
          add(MoneySymbol("Mozambique", "MT"))
          add(MoneySymbol("Myanmar", "K"))
          add(MoneySymbol("Namibia", "N$"))
          add(MoneySymbol("Nauru", "$"))
          add(MoneySymbol("Nepal", "रू"))
          add(MoneySymbol("Netherlands", "€"))
          add(MoneySymbol("New Zealand", "$"))
          add(MoneySymbol("Nicaragua", "C$"))
          add(MoneySymbol("Niger", "Fr"))
          add(MoneySymbol("Nigeria", "₦"))
          add(MoneySymbol("North Macedonia", "ден"))
          add(MoneySymbol("Norway", "kr"))
          add(MoneySymbol("Oman", "ر.ع."))
          add(MoneySymbol("Pakistan", "₨"))
          add(MoneySymbol("Palau", "$"))
          add(MoneySymbol("Palestine", "₪"))
          add(MoneySymbol("Panama", "B/."))
          add(MoneySymbol("Papua New Guinea", "K"))
          add(MoneySymbol("Paraguay", "₲"))
          add(MoneySymbol("Peru", "S/."))
          add(MoneySymbol("Philippines", "₱"))
          add(MoneySymbol("Poland", "zł"))
          add(MoneySymbol("Portugal", "€"))
          add(MoneySymbol("Qatar", "ر.ق"))
          add(MoneySymbol("Romania", "lei"))
          add(MoneySymbol("Russia", "₽"))
          add(MoneySymbol("Rwanda", "Fr"))
          add(MoneySymbol("Saint Kitts and Nevis", "$"))
          add(MoneySymbol("Saint Lucia", "$"))
          add(MoneySymbol("Saint Vincent and the Grenadines", "$"))
          add(MoneySymbol("Samoa", "T"))
          add(MoneySymbol("San Marino", "€"))
          add(MoneySymbol("São Tomé and Príncipe", "Db"))
          add(MoneySymbol("Saudi Arabia", "﷼"))
          add(MoneySymbol("Senegal", "CFA"))
          add(MoneySymbol("Serbia", "din"))
          add(MoneySymbol("Seychelles", "₨"))
          add(MoneySymbol("Sierra Leone", "Le"))
          add(MoneySymbol("Singapore", "S$"))
          add(MoneySymbol("Slovakia", "€"))
          add(MoneySymbol("Slovenia", "€"))
          add(MoneySymbol("Solomon Islands", "$"))
          add(MoneySymbol("Somalia", "Sh"))
          add(MoneySymbol("South Africa", "R"))
          add(MoneySymbol("South Sudan", "£"))
          add(MoneySymbol("Spain", "€"))
          add(MoneySymbol("Sri Lanka", "රු"))
          add(MoneySymbol("Sudan", "ج.س."))
          add(MoneySymbol("Suriname", "$"))
          add(MoneySymbol("Sweden", "kr"))
          add(MoneySymbol("Switzerland", "CHF"))
          add(MoneySymbol("Syria", "£ or ل.س"))
          add(MoneySymbol("Taiwan", "NT$"))
          add(MoneySymbol("Tajikistan", "ЅМ"))
          add(MoneySymbol("Tanzania", "Sh"))
          add(MoneySymbol("Thailand", "฿"))
          add(MoneySymbol("Togo", "Fr"))
          add(MoneySymbol("Tonga", "T$"))
          add(MoneySymbol("Trinidad and Tobago", "TT$"))
          add(MoneySymbol("Tunisia", "د.ت"))
          add(MoneySymbol("Turkey", "₺"))
          add(MoneySymbol("Turkmenistan", "m"))
          add(MoneySymbol("Tuvalu", "$"))
          add(MoneySymbol("Uganda", "Sh"))
          add(MoneySymbol("Ukraine", "₴"))
          add(MoneySymbol("United Arab Emirates", "د.إ"))
          add(MoneySymbol("United Kingdom", "£"))
          add(MoneySymbol("United States", "$"))
          add(MoneySymbol("Uruguay", "\$U"))
          add(MoneySymbol("Uzbekistan", "so'm"))
          add(MoneySymbol("Vanuatu", "Vt"))
          add(MoneySymbol("Vatican City", "€"))
          add(MoneySymbol("Venezuela", "Bs"))
          add(MoneySymbol("Vietnam", "₫"))
          add(MoneySymbol("Yemen", "﷼"))
          add(MoneySymbol("Zambia", "ZK"))
          add(MoneySymbol("Zimbabwe", "Z$"))
        }
    }
}